/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables;


import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.Carbon;
import org.carbon.sample.v2.ext.jooq.Keys;
import org.carbon.sample.v2.ext.jooq.tables.records.BlogRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blog extends TableImpl<BlogRecord> {

    private static final long serialVersionUID = -666363405;

    /**
     * The reference instance of <code>carbon.blog</code>
     */
    public static final Blog BLOG = new Blog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BlogRecord> getRecordType() {
        return BlogRecord.class;
    }

    /**
     * The column <code>carbon.blog.id</code>.
     */
    public final TableField<BlogRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('carbon.blog_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>carbon.blog.title</code>.
     */
    public final TableField<BlogRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>carbon.blog.summary</code>.
     */
    public final TableField<BlogRecord, String> SUMMARY = createField("summary", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>carbon.blog.content</code>.
     */
    public final TableField<BlogRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>carbon.blog</code> table reference
     */
    public Blog() {
        this("blog", null);
    }

    /**
     * Create an aliased <code>carbon.blog</code> table reference
     */
    public Blog(String alias) {
        this(alias, BLOG);
    }

    private Blog(String alias, Table<BlogRecord> aliased) {
        this(alias, aliased, null);
    }

    private Blog(String alias, Table<BlogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Carbon.CARBON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BlogRecord, Long> getIdentity() {
        return Keys.IDENTITY_BLOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BlogRecord> getPrimaryKey() {
        return Keys.BLOG_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BlogRecord>> getKeys() {
        return Arrays.<UniqueKey<BlogRecord>>asList(Keys.BLOG_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Blog as(String alias) {
        return new Blog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Blog rename(String name) {
        return new Blog(name, null);
    }
}
