/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.Carbondb;
import org.carbon.sample.v2.ext.jooq.Keys;
import org.carbon.sample.v2.ext.jooq.tables.records.RockettyRankingRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyRanking extends TableImpl<RockettyRankingRecord> {

    private static final long serialVersionUID = -1079742085;

    /**
     * The reference instance of <code>carbondb.rocketty_ranking</code>
     */
    public static final RockettyRanking ROCKETTY_RANKING = new RockettyRanking();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RockettyRankingRecord> getRecordType() {
        return RockettyRankingRecord.class;
    }

    /**
     * The column <code>carbondb.rocketty_ranking.id</code>.
     */
    public final TableField<RockettyRankingRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>carbondb.rocketty_ranking.internal_user_id</code>.
     */
    public final TableField<RockettyRankingRecord, String> INTERNAL_USER_ID = createField("internal_user_id", org.jooq.impl.SQLDataType.CHAR.length(127).nullable(false), this, "");

    /**
     * The column <code>carbondb.rocketty_ranking.score</code>.
     */
    public final TableField<RockettyRankingRecord, Integer> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>carbondb.rocketty_ranking.display_name</code>.
     */
    public final TableField<RockettyRankingRecord, String> DISPLAY_NAME = createField("display_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>carbondb.rocketty_ranking</code> table reference
     */
    public RockettyRanking() {
        this("rocketty_ranking", null);
    }

    /**
     * Create an aliased <code>carbondb.rocketty_ranking</code> table reference
     */
    public RockettyRanking(String alias) {
        this(alias, ROCKETTY_RANKING);
    }

    private RockettyRanking(String alias, Table<RockettyRankingRecord> aliased) {
        this(alias, aliased, null);
    }

    private RockettyRanking(String alias, Table<RockettyRankingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Carbondb.CARBONDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RockettyRankingRecord, Long> getIdentity() {
        return Keys.IDENTITY_ROCKETTY_RANKING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RockettyRankingRecord> getPrimaryKey() {
        return Keys.KEY_ROCKETTY_RANKING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RockettyRankingRecord>> getKeys() {
        return Arrays.<UniqueKey<RockettyRankingRecord>>asList(Keys.KEY_ROCKETTY_RANKING_PRIMARY, Keys.KEY_ROCKETTY_RANKING_ROCKETTY_RANKING_INTERNAL_USER_ID__INDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRanking as(String alias) {
        return new RockettyRanking(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RockettyRanking rename(String name) {
        return new RockettyRanking(name, null);
    }
}
