/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.Asset;
import org.carbon.sample.ext.jooq.tables.Lecturer;
import org.carbon.sample.ext.jooq.tables.LecturerApplyHistory;
import org.carbon.sample.ext.jooq.tables.LecturerRoom;
import org.carbon.sample.ext.jooq.tables.LecturerSchedule;
import org.carbon.sample.ext.jooq.tables.Product;
import org.carbon.sample.ext.jooq.tables.Role;
import org.carbon.sample.ext.jooq.tables.SchemaVersion;
import org.carbon.sample.ext.jooq.tables.Student;
import org.carbon.sample.ext.jooq.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Carbondb extends SchemaImpl {

    private static final long serialVersionUID = 1716233354;

    /**
     * The reference instance of <code>carbondb</code>
     */
    public static final Carbondb CARBONDB = new Carbondb();

    /**
     * The table <code>carbondb.asset</code>.
     */
    public final Asset ASSET = org.carbon.sample.ext.jooq.tables.Asset.ASSET;

    /**
     * The table <code>carbondb.lecturer</code>.
     */
    public final Lecturer LECTURER = org.carbon.sample.ext.jooq.tables.Lecturer.LECTURER;

    /**
     * The table <code>carbondb.lecturer_apply_history</code>.
     */
    public final LecturerApplyHistory LECTURER_APPLY_HISTORY = org.carbon.sample.ext.jooq.tables.LecturerApplyHistory.LECTURER_APPLY_HISTORY;

    /**
     * The table <code>carbondb.lecturer_room</code>.
     */
    public final LecturerRoom LECTURER_ROOM = org.carbon.sample.ext.jooq.tables.LecturerRoom.LECTURER_ROOM;

    /**
     * The table <code>carbondb.lecturer_schedule</code>.
     */
    public final LecturerSchedule LECTURER_SCHEDULE = org.carbon.sample.ext.jooq.tables.LecturerSchedule.LECTURER_SCHEDULE;

    /**
     * The table <code>carbondb.product</code>.
     */
    public final Product PRODUCT = org.carbon.sample.ext.jooq.tables.Product.PRODUCT;

    /**
     * The table <code>carbondb.role</code>.
     */
    public final Role ROLE = org.carbon.sample.ext.jooq.tables.Role.ROLE;

    /**
     * The table <code>carbondb.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = org.carbon.sample.ext.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>carbondb.student</code>.
     */
    public final Student STUDENT = org.carbon.sample.ext.jooq.tables.Student.STUDENT;

    /**
     * The table <code>carbondb.user</code>.
     */
    public final User USER = org.carbon.sample.ext.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Carbondb() {
        super("carbondb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Asset.ASSET,
                Lecturer.LECTURER,
                LecturerApplyHistory.LECTURER_APPLY_HISTORY,
                LecturerRoom.LECTURER_ROOM,
                LecturerSchedule.LECTURER_SCHEDULE,
                Product.PRODUCT,
                Role.ROLE,
                SchemaVersion.SCHEMA_VERSION,
                Student.STUDENT,
                User.USER);
    }
}
