/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq;


import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.Asset;
import org.carbon.sample.ext.jooq.tables.Lecturer;
import org.carbon.sample.ext.jooq.tables.LecturerApplyHistory;
import org.carbon.sample.ext.jooq.tables.LecturerRoom;
import org.carbon.sample.ext.jooq.tables.LecturerSchedule;
import org.carbon.sample.ext.jooq.tables.Product;
import org.carbon.sample.ext.jooq.tables.Role;
import org.carbon.sample.ext.jooq.tables.SchemaVersion;
import org.carbon.sample.ext.jooq.tables.Student;
import org.carbon.sample.ext.jooq.tables.User;


/**
 * Convenience access to all tables in carbondb
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>carbondb.asset</code>.
     */
    public static final Asset ASSET = org.carbon.sample.ext.jooq.tables.Asset.ASSET;

    /**
     * The table <code>carbondb.lecturer</code>.
     */
    public static final Lecturer LECTURER = org.carbon.sample.ext.jooq.tables.Lecturer.LECTURER;

    /**
     * The table <code>carbondb.lecturer_apply_history</code>.
     */
    public static final LecturerApplyHistory LECTURER_APPLY_HISTORY = org.carbon.sample.ext.jooq.tables.LecturerApplyHistory.LECTURER_APPLY_HISTORY;

    /**
     * The table <code>carbondb.lecturer_room</code>.
     */
    public static final LecturerRoom LECTURER_ROOM = org.carbon.sample.ext.jooq.tables.LecturerRoom.LECTURER_ROOM;

    /**
     * The table <code>carbondb.lecturer_schedule</code>.
     */
    public static final LecturerSchedule LECTURER_SCHEDULE = org.carbon.sample.ext.jooq.tables.LecturerSchedule.LECTURER_SCHEDULE;

    /**
     * The table <code>carbondb.product</code>.
     */
    public static final Product PRODUCT = org.carbon.sample.ext.jooq.tables.Product.PRODUCT;

    /**
     * The table <code>carbondb.role</code>.
     */
    public static final Role ROLE = org.carbon.sample.ext.jooq.tables.Role.ROLE;

    /**
     * The table <code>carbondb.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = org.carbon.sample.ext.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>carbondb.student</code>.
     */
    public static final Student STUDENT = org.carbon.sample.ext.jooq.tables.Student.STUDENT;

    /**
     * The table <code>carbondb.user</code>.
     */
    public static final User USER = org.carbon.sample.ext.jooq.tables.User.USER;
}
