/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in carbon
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>carbon.auth_client_id_seq</code>
     */
    public static final Sequence<Long> AUTH_CLIENT_ID_SEQ = new SequenceImpl<Long>("auth_client_id_seq", Carbon.CARBON, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>carbon.blog_id_seq</code>
     */
    public static final Sequence<Long> BLOG_ID_SEQ = new SequenceImpl<Long>("blog_id_seq", Carbon.CARBON, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>carbon.todo_id_seq</code>
     */
    public static final Sequence<Long> TODO_ID_SEQ = new SequenceImpl<Long>("todo_id_seq", Carbon.CARBON, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>carbon.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Carbon.CARBON, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
