/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.heroku.ext.jooq.tables.interfaces.IBlog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blog implements IBlog {

    private static final long serialVersionUID = 277762741;

    private Integer id;
    private String  title;
    private String  summary;
    private String  content;

    public Blog() {}

    public Blog(Blog value) {
        this.id = value.id;
        this.title = value.title;
        this.summary = value.summary;
        this.content = value.content;
    }

    public Blog(
        Integer id,
        String  title,
        String  summary,
        String  content
    ) {
        this.id = id;
        this.title = title;
        this.summary = summary;
        this.content = content;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String getSummary() {
        return this.summary;
    }

    @Override
    public void setSummary(String summary) {
        this.summary = summary;
    }

    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Blog (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(summary);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IBlog from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setSummary(from.getSummary());
        setContent(from.getContent());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IBlog> E into(E into) {
        into.from(this);
        return into;
    }
}
