/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.heroku.ext.jooq.tables.interfaces.ITask;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements ITask {

    private static final long serialVersionUID = -1717989199;

    private Long    id;
    private String  title;
    private String  description;
    private Long    userId;
    private Boolean available;
    private Boolean finished;

    public Task() {}

    public Task(Task value) {
        this.id = value.id;
        this.title = value.title;
        this.description = value.description;
        this.userId = value.userId;
        this.available = value.available;
        this.finished = value.finished;
    }

    public Task(
        Long    id,
        String  title,
        String  description,
        Long    userId,
        Boolean available,
        Boolean finished
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.userId = userId;
        this.available = available;
        this.finished = finished;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public Boolean getAvailable() {
        return this.available;
    }

    @Override
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    @Override
    public Boolean getFinished() {
        return this.finished;
    }

    @Override
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(userId);
        sb.append(", ").append(available);
        sb.append(", ").append(finished);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITask from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setUserId(from.getUserId());
        setAvailable(from.getAvailable());
        setFinished(from.getFinished());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITask> E into(E into) {
        into.from(this);
        return into;
    }
}
