/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.heroku.ext.jooq.tables.interfaces.ITodo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todo implements ITodo {

    private static final long serialVersionUID = -1992571316;

    private Long    id;
    private String  text;
    private Long    userId;
    private Boolean available;

    public Todo() {}

    public Todo(Todo value) {
        this.id = value.id;
        this.text = value.text;
        this.userId = value.userId;
        this.available = value.available;
    }

    public Todo(
        Long    id,
        String  text,
        Long    userId,
        Boolean available
    ) {
        this.id = id;
        this.text = text;
        this.userId = userId;
        this.available = available;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getText() {
        return this.text;
    }

    @Override
    public void setText(String text) {
        this.text = text;
    }

    @Override
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public Boolean getAvailable() {
        return this.available;
    }

    @Override
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Todo (");

        sb.append(id);
        sb.append(", ").append(text);
        sb.append(", ").append(userId);
        sb.append(", ").append(available);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITodo from) {
        setId(from.getId());
        setText(from.getText());
        setUserId(from.getUserId());
        setAvailable(from.getAvailable());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITodo> E into(E into) {
        into.from(this);
        return into;
    }
}
