web:
  port: 8927
  maxHeaderSize: 512000 #500KB
  maxContentSize: 2097152 #2MB
  customError:
    notFound: /error/404
    serverError: /error/500
persistent:
  dataSource:
    host: rdb.carbon-v2.local
    db: carbondb
    user: carbon
    password: carbonpw
    port: 43306
