/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.records;


import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.Asset;
import org.carbon.sample.ext.jooq.tables.interfaces.IAsset;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetRecord extends UpdatableRecordImpl<AssetRecord> implements Record3<Long, String, String>, IAsset {

    private static final long serialVersionUID = 914260810;

    /**
     * Setter for <code>carbondb.asset.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbondb.asset.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>carbondb.asset.asset_path</code>.
     */
    @Override
    public void setAssetPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>carbondb.asset.asset_path</code>.
     */
    @Override
    public String getAssetPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>carbondb.asset.asset_type</code>.
     */
    @Override
    public void setAssetType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>carbondb.asset.asset_type</code>.
     */
    @Override
    public String getAssetType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Asset.ASSET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Asset.ASSET.ASSET_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Asset.ASSET.ASSET_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAssetPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAssetType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssetRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssetRecord value2(String value) {
        setAssetPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssetRecord value3(String value) {
        setAssetType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssetRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAsset from) {
        setId(from.getId());
        setAssetPath(from.getAssetPath());
        setAssetType(from.getAssetType());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAsset> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetRecord
     */
    public AssetRecord() {
        super(Asset.ASSET);
    }

    /**
     * Create a detached, initialised AssetRecord
     */
    public AssetRecord(Long id, String assetPath, String assetType) {
        super(Asset.ASSET);

        set(0, id);
        set(1, assetPath);
        set(2, assetType);
    }
}
