/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.records;


import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.LecturerApplyHistory;
import org.carbon.sample.ext.jooq.tables.interfaces.ILecturerApplyHistory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LecturerApplyHistoryRecord extends UpdatableRecordImpl<LecturerApplyHistoryRecord> implements Record1<Long>, ILecturerApplyHistory {

    private static final long serialVersionUID = -394711531;

    /**
     * Setter for <code>carbondb.lecturer_apply_history.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbondb.lecturer_apply_history.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LecturerApplyHistory.LECTURER_APPLY_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerApplyHistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerApplyHistoryRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ILecturerApplyHistory from) {
        setId(from.getId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ILecturerApplyHistory> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LecturerApplyHistoryRecord
     */
    public LecturerApplyHistoryRecord() {
        super(LecturerApplyHistory.LECTURER_APPLY_HISTORY);
    }

    /**
     * Create a detached, initialised LecturerApplyHistoryRecord
     */
    public LecturerApplyHistoryRecord(Long id) {
        super(LecturerApplyHistory.LECTURER_APPLY_HISTORY);

        set(0, id);
    }
}
