/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.LecturerRoom;
import org.carbon.sample.ext.jooq.tables.interfaces.ILecturerRoom;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LecturerRoomRecord extends UpdatableRecordImpl<LecturerRoomRecord> implements Record6<Long, Long, String, String, LocalDateTime, LocalDateTime>, ILecturerRoom {

    private static final long serialVersionUID = -11015687;

    /**
     * Setter for <code>carbondb.lecturer_room.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbondb.lecturer_room.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>carbondb.lecturer_room.lecturer_id</code>.
     */
    @Override
    public void setLecturerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>carbondb.lecturer_room.lecturer_id</code>.
     */
    @Override
    public Long getLecturerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>carbondb.lecturer_room.room_name</code>.
     */
    @Override
    public void setRoomName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>carbondb.lecturer_room.room_name</code>.
     */
    @Override
    public String getRoomName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>carbondb.lecturer_room.room_detail</code>.
     */
    @Override
    public void setRoomDetail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>carbondb.lecturer_room.room_detail</code>.
     */
    @Override
    public String getRoomDetail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>carbondb.lecturer_room.begin_datetime</code>.
     */
    @Override
    public void setBeginDatetime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>carbondb.lecturer_room.begin_datetime</code>.
     */
    @Override
    public LocalDateTime getBeginDatetime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>carbondb.lecturer_room.end_datetime</code>.
     */
    @Override
    public void setEndDatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>carbondb.lecturer_room.end_datetime</code>.
     */
    @Override
    public LocalDateTime getEndDatetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LecturerRoom.LECTURER_ROOM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return LecturerRoom.LECTURER_ROOM.LECTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return LecturerRoom.LECTURER_ROOM.ROOM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LecturerRoom.LECTURER_ROOM.ROOM_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return LecturerRoom.LECTURER_ROOM.BEGIN_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return LecturerRoom.LECTURER_ROOM.END_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getLecturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRoomDetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getBeginDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getEndDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerRoomRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerRoomRecord value2(Long value) {
        setLecturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerRoomRecord value3(String value) {
        setRoomName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerRoomRecord value4(String value) {
        setRoomDetail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerRoomRecord value5(LocalDateTime value) {
        setBeginDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerRoomRecord value6(LocalDateTime value) {
        setEndDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LecturerRoomRecord values(Long value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ILecturerRoom from) {
        setId(from.getId());
        setLecturerId(from.getLecturerId());
        setRoomName(from.getRoomName());
        setRoomDetail(from.getRoomDetail());
        setBeginDatetime(from.getBeginDatetime());
        setEndDatetime(from.getEndDatetime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ILecturerRoom> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LecturerRoomRecord
     */
    public LecturerRoomRecord() {
        super(LecturerRoom.LECTURER_ROOM);
    }

    /**
     * Create a detached, initialised LecturerRoomRecord
     */
    public LecturerRoomRecord(Long id, Long lecturerId, String roomName, String roomDetail, LocalDateTime beginDatetime, LocalDateTime endDatetime) {
        super(LecturerRoom.LECTURER_ROOM);

        set(0, id);
        set(1, lecturerId);
        set(2, roomName);
        set(3, roomDetail);
        set(4, beginDatetime);
        set(5, endDatetime);
    }
}
