/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.carbon.component.annotation.Component;
import org.carbon.sample.v2.ext.jooq.tables.AuthClient;
import org.carbon.sample.v2.ext.jooq.tables.records.AuthClientRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Component
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthClientDao extends DAOImpl<AuthClientRecord, org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient, Long> {

    /**
     * Create a new AuthClientDao without any configuration
     */
    public AuthClientDao() {
        super(AuthClient.AUTH_CLIENT, org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient.class);
    }

    /**
     * Create a new AuthClientDao with an attached configuration
     */
    public AuthClientDao(Configuration configuration) {
        super(AuthClient.AUTH_CLIENT, org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient> fetchById(Long... values) {
        return fetch(AuthClient.AUTH_CLIENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient fetchOneById(Long value) {
        return fetchOne(AuthClient.AUTH_CLIENT.ID, value);
    }

    /**
     * Fetch records that have <code>client_host IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient> fetchByClientHost(String... values) {
        return fetch(AuthClient.AUTH_CLIENT.CLIENT_HOST, values);
    }

    /**
     * Fetch a unique record that has <code>client_host = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient fetchOneByClientHost(String value) {
        return fetchOne(AuthClient.AUTH_CLIENT.CLIENT_HOST, value);
    }

    /**
     * Fetch records that have <code>client_id IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient> fetchByClientId(String... values) {
        return fetch(AuthClient.AUTH_CLIENT.CLIENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>client_id = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.AuthClient fetchOneByClientId(String value) {
        return fetchOne(AuthClient.AUTH_CLIENT.CLIENT_ID, value);
    }
}
