/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.daos;


import java.util.List;
import javax.annotation.Generated;

import org.carbon.component.annotation.Component;
import org.carbon.sample.v2.ext.jooq.tables.Blog;
import org.carbon.sample.v2.ext.jooq.tables.records.BlogRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Component
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogDao extends DAOImpl<BlogRecord, org.carbon.sample.v2.ext.jooq.tables.pojos.Blog, Long> {

    /**
     * Create a new BlogDao without any configuration
     */
    public BlogDao() {
        super(Blog.BLOG, org.carbon.sample.v2.ext.jooq.tables.pojos.Blog.class);
    }

    /**
     * Create a new BlogDao with an attached configuration
     */
    public BlogDao(Configuration configuration) {
        super(Blog.BLOG, org.carbon.sample.v2.ext.jooq.tables.pojos.Blog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.v2.ext.jooq.tables.pojos.Blog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.Blog> fetchById(Long... values) {
        return fetch(Blog.BLOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.Blog fetchOneById(Long value) {
        return fetchOne(Blog.BLOG.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.Blog> fetchByTitle(String... values) {
        return fetch(Blog.BLOG.TITLE, values);
    }

    /**
     * Fetch records that have <code>summary IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.Blog> fetchBySummary(String... values) {
        return fetch(Blog.BLOG.SUMMARY, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.Blog> fetchByContent(String... values) {
        return fetch(Blog.BLOG.CONTENT, values);
    }
}
