/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.carbon.component.annotation.Component;
import org.carbon.sample.v2.ext.jooq.tables.RockettyUser;
import org.carbon.sample.v2.ext.jooq.tables.records.RockettyUserRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Component
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyUserDao extends DAOImpl<RockettyUserRecord, org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser, Long> {

    /**
     * Create a new RockettyUserDao without any configuration
     */
    public RockettyUserDao() {
        super(RockettyUser.ROCKETTY_USER, org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser.class);
    }

    /**
     * Create a new RockettyUserDao with an attached configuration
     */
    public RockettyUserDao(Configuration configuration) {
        super(RockettyUser.ROCKETTY_USER, org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser> fetchById(Long... values) {
        return fetch(RockettyUser.ROCKETTY_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser fetchOneById(Long value) {
        return fetchOne(RockettyUser.ROCKETTY_USER.ID, value);
    }

    /**
     * Fetch records that have <code>rocketty_auth_client_id IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser> fetchByRockettyAuthClientId(Long... values) {
        return fetch(RockettyUser.ROCKETTY_USER.ROCKETTY_AUTH_CLIENT_ID, values);
    }

    /**
     * Fetch records that have <code>display_name IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser> fetchByDisplayName(String... values) {
        return fetch(RockettyUser.ROCKETTY_USER.DISPLAY_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>display_name = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyUser fetchOneByDisplayName(String value) {
        return fetchOne(RockettyUser.ROCKETTY_USER.DISPLAY_NAME, value);
    }
}
