/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.carbon.component.annotation.Component;
import org.carbon.sample.v2.ext.jooq.tables.RockettyAuthClient;
import org.carbon.sample.v2.ext.jooq.tables.records.RockettyAuthClientRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Component
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyAuthClientDao extends DAOImpl<RockettyAuthClientRecord, org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient, Long> {

    /**
     * Create a new RockettyAuthClientDao without any configuration
     */
    public RockettyAuthClientDao() {
        super(RockettyAuthClient.ROCKETTY_AUTH_CLIENT, org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient.class);
    }

    /**
     * Create a new RockettyAuthClientDao with an attached configuration
     */
    public RockettyAuthClientDao(Configuration configuration) {
        super(RockettyAuthClient.ROCKETTY_AUTH_CLIENT, org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient> fetchById(Long... values) {
        return fetch(RockettyAuthClient.ROCKETTY_AUTH_CLIENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient fetchOneById(Long value) {
        return fetchOne(RockettyAuthClient.ROCKETTY_AUTH_CLIENT.ID, value);
    }

    /**
     * Fetch records that have <code>client_id IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient> fetchByClientId(String... values) {
        return fetch(RockettyAuthClient.ROCKETTY_AUTH_CLIENT.CLIENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>client_id = value</code>
     */
    public org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient fetchOneByClientId(String value) {
        return fetchOne(RockettyAuthClient.ROCKETTY_AUTH_CLIENT.CLIENT_ID, value);
    }

    /**
     * Fetch records that have <code>client_secret IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient> fetchByClientSecret(String... values) {
        return fetch(RockettyAuthClient.ROCKETTY_AUTH_CLIENT.CLIENT_SECRET, values);
    }

    /**
     * Fetch records that have <code>valid IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient> fetchByValid(Boolean... values) {
        return fetch(RockettyAuthClient.ROCKETTY_AUTH_CLIENT.VALID, values);
    }

    /**
     * Fetch records that have <code>expire_at IN (values)</code>
     */
    public List<org.carbon.sample.v2.ext.jooq.tables.pojos.RockettyAuthClient> fetchByExpireAt(LocalDateTime... values) {
        return fetch(RockettyAuthClient.ROCKETTY_AUTH_CLIENT.EXPIRE_AT, values);
    }
}
