/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.records;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.RockettyRanking;
import org.carbon.sample.v2.ext.jooq.tables.interfaces.IRockettyRanking;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyRankingRecord extends UpdatableRecordImpl<RockettyRankingRecord> implements Record4<Long, String, Integer, String>, IRockettyRanking {

    private static final long serialVersionUID = 1926266036;

    /**
     * Setter for <code>carbondb.rocketty_ranking.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_ranking.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>carbondb.rocketty_ranking.internal_user_id</code>.
     */
    @Override
    public void setInternalUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_ranking.internal_user_id</code>.
     */
    @Override
    public String getInternalUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>carbondb.rocketty_ranking.score</code>.
     */
    @Override
    public void setScore(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_ranking.score</code>.
     */
    @Override
    public Integer getScore() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>carbondb.rocketty_ranking.display_name</code>.
     */
    @Override
    public void setDisplayName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_ranking.display_name</code>.
     */
    @Override
    public String getDisplayName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RockettyRanking.ROCKETTY_RANKING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RockettyRanking.ROCKETTY_RANKING.INTERNAL_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RockettyRanking.ROCKETTY_RANKING.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RockettyRanking.ROCKETTY_RANKING.DISPLAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getInternalUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord value2(String value) {
        setInternalUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord value3(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord value4(String value) {
        setDisplayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord values(Long value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IRockettyRanking from) {
        setId(from.getId());
        setInternalUserId(from.getInternalUserId());
        setScore(from.getScore());
        setDisplayName(from.getDisplayName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IRockettyRanking> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RockettyRankingRecord
     */
    public RockettyRankingRecord() {
        super(RockettyRanking.ROCKETTY_RANKING);
    }

    /**
     * Create a detached, initialised RockettyRankingRecord
     */
    public RockettyRankingRecord(Long id, String internalUserId, Integer score, String displayName) {
        super(RockettyRanking.ROCKETTY_RANKING);

        set(0, id);
        set(1, internalUserId);
        set(2, score);
        set(3, displayName);
    }
}
