/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.records;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.RockettyRanking;
import org.carbon.sample.v2.ext.jooq.tables.interfaces.IRockettyRanking;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyRankingRecord extends UpdatableRecordImpl<RockettyRankingRecord> implements Record3<Long, Long, Integer>, IRockettyRanking {

    private static final long serialVersionUID = -441921137;

    /**
     * Setter for <code>carbondb.rocketty_ranking.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_ranking.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>carbondb.rocketty_ranking.rocketty_user_id</code>.
     */
    public void setRockettyUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_ranking.rocketty_user_id</code>.
     */
    @Override
    public Long getRockettyUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>carbondb.rocketty_ranking.score</code>.
     */
    public void setScore(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_ranking.score</code>.
     */
    @Override
    public Integer getScore() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RockettyRanking.ROCKETTY_RANKING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RockettyRanking.ROCKETTY_RANKING.ROCKETTY_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RockettyRanking.ROCKETTY_RANKING.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRockettyUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord value2(Long value) {
        setRockettyUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord value3(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyRankingRecord values(Long value1, Long value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IRockettyRanking from) {
        setId(from.getId());
        setRockettyUserId(from.getRockettyUserId());
        setScore(from.getScore());
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RockettyRankingRecord
     */
    public RockettyRankingRecord() {
        super(RockettyRanking.ROCKETTY_RANKING);
    }

    /**
     * Create a detached, initialised RockettyRankingRecord
     */
    public RockettyRankingRecord(Long id, Long rockettyUserId, Integer score) {
        super(RockettyRanking.ROCKETTY_RANKING);

        set(0, id);
        set(1, rockettyUserId);
        set(2, score);
    }
}
