/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.records;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.RockettyUser;
import org.carbon.sample.v2.ext.jooq.tables.interfaces.IRockettyUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyUserRecord extends UpdatableRecordImpl<RockettyUserRecord> implements Record3<Long, Long, String>, IRockettyUser {

    private static final long serialVersionUID = -344191147;

    /**
     * Setter for <code>carbondb.rocketty_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_user.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>carbondb.rocketty_user.rocketty_auth_client_id</code>.
     */
    public void setRockettyAuthClientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_user.rocketty_auth_client_id</code>.
     */
    @Override
    public Long getRockettyAuthClientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>carbondb.rocketty_user.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>carbondb.rocketty_user.display_name</code>.
     */
    @Override
    public String getDisplayName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RockettyUser.ROCKETTY_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RockettyUser.ROCKETTY_USER.ROCKETTY_AUTH_CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RockettyUser.ROCKETTY_USER.DISPLAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRockettyAuthClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyUserRecord value2(Long value) {
        setRockettyAuthClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyUserRecord value3(String value) {
        setDisplayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RockettyUserRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IRockettyUser from) {
        setId(from.getId());
        setRockettyAuthClientId(from.getRockettyAuthClientId());
        setDisplayName(from.getDisplayName());
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RockettyUserRecord
     */
    public RockettyUserRecord() {
        super(RockettyUser.ROCKETTY_USER);
    }

    /**
     * Create a detached, initialised RockettyUserRecord
     */
    public RockettyUserRecord(Long id, Long rockettyAuthClientId, String displayName) {
        super(RockettyUser.ROCKETTY_USER);

        set(0, id);
        set(1, rockettyAuthClientId);
        set(2, displayName);
    }
}
