/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.AuthClient;
import org.carbon.sample.v2.ext.jooq.tables.FlywaySchemaHistory;
import org.carbon.sample.v2.ext.jooq.tables.User;


/**
 * Convenience access to all tables in carbondb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>carbondb.auth_client</code>.
     */
    public static final AuthClient AUTH_CLIENT = org.carbon.sample.v2.ext.jooq.tables.AuthClient.AUTH_CLIENT;

    /**
     * The table <code>carbondb.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = org.carbon.sample.v2.ext.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>carbondb.user</code>.
     */
    public static final User USER = org.carbon.sample.v2.ext.jooq.tables.User.USER;
}
