web:
  port: 8080
  resource:
    directory: static
    outPath: static
  maxHeaderSize: 512000 #500KB
  maxContentSize: 2097152 #2MB
  customError:
      notFound: /error/404
      serverError: /error/500
persistent:
  implementation: jooq # jooq or hibernate

sample:
  heroku:
    db:
      url: postgres://root:password@carbon.heroku.rdb:25432/carbon