---
- name: Install nginx
  apt:
    name: nginx={{ nginx_version }}
    update_cache: true
- name: Add user for nginx
  user:
    name: "{{ nginx_user }}"
    shell: /bin/false
    createhome: false
    state: present
- name: Copy Nginx app conf file
  template:
    src: templates/{{ item.key }}
    dest: /etc/nginx/{{ item.value }}
    force: true
  with_dict:
    nginx.conf.j2: nginx.conf
    app_server.conf.j2: conf.d/app_server.conf
- name: Validate Nginx conf file
  command: nginx -t -c /etc/nginx/nginx.conf
- name: Restart Nginx service
  command: service nginx start
