/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.records;


import javax.annotation.Generated;

import org.carbon.sample.heroku.ext.jooq.tables.Blog;
import org.carbon.sample.heroku.ext.jooq.tables.interfaces.IBlog;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogRecord extends UpdatableRecordImpl<BlogRecord> implements Record4<Long, String, String, String>, IBlog {

    private static final long serialVersionUID = -1473769841;

    /**
     * Setter for <code>carbon.blog.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbon.blog.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>carbon.blog.title</code>.
     */
    @Override
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>carbon.blog.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>carbon.blog.summary</code>.
     */
    @Override
    public void setSummary(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>carbon.blog.summary</code>.
     */
    @Override
    public String getSummary() {
        return (String) get(2);
    }

    /**
     * Setter for <code>carbon.blog.content</code>.
     */
    @Override
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>carbon.blog.content</code>.
     */
    @Override
    public String getContent() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Blog.BLOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Blog.BLOG.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Blog.BLOG.SUMMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Blog.BLOG.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSummary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogRecord value3(String value) {
        setSummary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IBlog from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setSummary(from.getSummary());
        setContent(from.getContent());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IBlog> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlogRecord
     */
    public BlogRecord() {
        super(Blog.BLOG);
    }

    /**
     * Create a detached, initialised BlogRecord
     */
    public BlogRecord(Long id, String title, String summary, String content) {
        super(Blog.BLOG);

        set(0, id);
        set(1, title);
        set(2, summary);
        set(3, content);
    }
}
