/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.records;


import javax.annotation.Generated;

import org.carbon.sample.heroku.ext.jooq.tables.Todo;
import org.carbon.sample.heroku.ext.jooq.tables.interfaces.ITodo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoRecord extends UpdatableRecordImpl<TodoRecord> implements Record4<Long, String, Long, Boolean>, ITodo {

    private static final long serialVersionUID = 1763215817;

    /**
     * Setter for <code>carbon.todo.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>carbon.todo.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>carbon.todo.text</code>.
     */
    @Override
    public void setText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>carbon.todo.text</code>.
     */
    @Override
    public String getText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>carbon.todo.user_id</code>.
     */
    @Override
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>carbon.todo.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>carbon.todo.available</code>.
     */
    @Override
    public void setAvailable(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>carbon.todo.available</code>.
     */
    @Override
    public Boolean getAvailable() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Long, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Todo.TODO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Todo.TODO.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Todo.TODO.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Todo.TODO.AVAILABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value2(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord value4(Boolean value) {
        setAvailable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TodoRecord values(Long value1, String value2, Long value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITodo from) {
        setId(from.getId());
        setText(from.getText());
        setUserId(from.getUserId());
        setAvailable(from.getAvailable());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITodo> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodoRecord
     */
    public TodoRecord() {
        super(Todo.TODO);
    }

    /**
     * Create a detached, initialised TodoRecord
     */
    public TodoRecord(Long id, String text, Long userId, Boolean available) {
        super(Todo.TODO);

        set(0, id);
        set(1, text);
        set(2, userId);
        set(3, available);
    }
}
