web:
  port: 7927
  resource:
    directory: static
    outPath: static
  maxHeaderSize: 512000 #500KB
  maxContentSize: 2097152 #2MB
persistent:
  implementation: jooq # jooq or hibernate
  dataSource:
    dialect: mysql # mysql or postgresql
    host: 127.0.0.1
    db: carbondb
    user: root
    password: password
    port: 23306

sample:
  redis:
    host: 127.0.0.1
    port: 26379
