web:
  port: {$PORT}
  resourceDirectory: static
  resourceOutPath: static
  maxHeaderSize: 512000 #500KB
  maxContentSize: 2097152 #2MB
persistent:
  implementation: jooq # jooq or hibernate

sample:
  redis:
    host: 127.0.0.1
    port: 26379
  db:
    url: ${DATABASE_URL}