/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAuthClient extends Serializable {

    /**
     * Getter for <code>carbondb.auth_client.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>carbondb.auth_client.client_host</code>.
     */
    public String getClientHost();

    /**
     * Getter for <code>carbondb.auth_client.client_id</code>.
     */
    public String getClientId();
}
