/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.interfaces;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAuthClient extends Serializable {

    /**
     * Setter for <code>carbon.auth_client.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>carbon.auth_client.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>carbon.auth_client.client_host</code>.
     */
    public void setClientHost(String value);

    /**
     * Getter for <code>carbon.auth_client.client_host</code>.
     */
    public String getClientHost();

    /**
     * Setter for <code>carbon.auth_client.client_id</code>.
     */
    public void setClientId(String value);

    /**
     * Getter for <code>carbon.auth_client.client_id</code>.
     */
    public String getClientId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAuthClient
     */
    public void from(org.carbon.sample.v2.ext.jooq.tables.interfaces.IAuthClient from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAuthClient
     */
    public <E extends org.carbon.sample.v2.ext.jooq.tables.interfaces.IAuthClient> E into(E into);
}
