/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRockettyAuthClient extends Serializable {

    /**
     * Getter for <code>carbondb.rocketty_auth_client.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>carbondb.rocketty_auth_client.client_id</code>.
     */
    public String getClientId();

    /**
     * Getter for <code>carbondb.rocketty_auth_client.client_secret</code>.
     */
    public String getClientSecret();

    /**
     * Getter for <code>carbondb.rocketty_auth_client.valid</code>.
     */
    public Boolean getValid();

    /**
     * Getter for <code>carbondb.rocketty_auth_client.expire_at</code>.
     */
    public LocalDateTime getExpireAt();
}
