/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRockettyRanking extends Serializable {

    /**
     * Getter for <code>carbondb.rocketty_ranking.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>carbondb.rocketty_ranking.rocketty_user_id</code>.
     */
    public Long getRockettyUserId();

    /**
     * Getter for <code>carbondb.rocketty_ranking.score</code>.
     */
    public Integer getScore();
}
