/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISchemaVersion extends Serializable {

    /**
     * Setter for <code>carbon.schema_version.installed_rank</code>.
     */
    public void setInstalledRank(Integer value);

    /**
     * Getter for <code>carbon.schema_version.installed_rank</code>.
     */
    public Integer getInstalledRank();

    /**
     * Setter for <code>carbon.schema_version.version</code>.
     */
    public void setVersion(String value);

    /**
     * Getter for <code>carbon.schema_version.version</code>.
     */
    public String getVersion();

    /**
     * Setter for <code>carbon.schema_version.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>carbon.schema_version.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>carbon.schema_version.type</code>.
     */
    public void setType(String value);

    /**
     * Getter for <code>carbon.schema_version.type</code>.
     */
    public String getType();

    /**
     * Setter for <code>carbon.schema_version.script</code>.
     */
    public void setScript(String value);

    /**
     * Getter for <code>carbon.schema_version.script</code>.
     */
    public String getScript();

    /**
     * Setter for <code>carbon.schema_version.checksum</code>.
     */
    public void setChecksum(Integer value);

    /**
     * Getter for <code>carbon.schema_version.checksum</code>.
     */
    public Integer getChecksum();

    /**
     * Setter for <code>carbon.schema_version.installed_by</code>.
     */
    public void setInstalledBy(String value);

    /**
     * Getter for <code>carbon.schema_version.installed_by</code>.
     */
    public String getInstalledBy();

    /**
     * Setter for <code>carbon.schema_version.installed_on</code>.
     */
    public void setInstalledOn(Timestamp value);

    /**
     * Getter for <code>carbon.schema_version.installed_on</code>.
     */
    public Timestamp getInstalledOn();

    /**
     * Setter for <code>carbon.schema_version.execution_time</code>.
     */
    public void setExecutionTime(Integer value);

    /**
     * Getter for <code>carbon.schema_version.execution_time</code>.
     */
    public Integer getExecutionTime();

    /**
     * Setter for <code>carbon.schema_version.success</code>.
     */
    public void setSuccess(Boolean value);

    /**
     * Getter for <code>carbon.schema_version.success</code>.
     */
    public Boolean getSuccess();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISchemaVersion
     */
    public void from(org.carbon.sample.v2.ext.jooq.tables.interfaces.ISchemaVersion from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISchemaVersion
     */
    public <E extends org.carbon.sample.v2.ext.jooq.tables.interfaces.ISchemaVersion> E into(E into);
}
