---
- name: Install required modules for install
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - software-properties-common
    - dirmngr
    - python-mysqldb
- name: Add repository key to the system
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"
- name: Resolve MariaDB repository
  apt_repository:
    repo: "deb [arch=amd64,i386,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.2/debian stretch main"
    state: present
- name: Install DB Server
  apt:
    name: mariadb-server={{ mariadb_version }}
    state: present
    update_cache: yes
- name: Set configuration files
  copy:
    src: templates/
    dest: /etc/mysql/
    owner: root
    group: root
    mode: 0755
- name: Start MariaDB service
  service:
    name: mysql
    state: started
- name: Change Root password
  mysql_user:
    host: "localhost"
    name: root
    password: "{{ mariadb_root_password }}"
    state: present
- name: Create application user for database connection
  mysql_user:
    host: "localhost"
    name: "{{ mariadb_app_username }}"
    password: "{{ mariadb_app_password }}"
    priv: "*.*:CREATE,SELECT,INSERT,UPDATE,DELETE,INDEX"
    state: present
- name: Setup initial schema
  mysql_db:
      name: "{{ mariadb_app_database }}"
      state: present
- name: Restart MariaDB service
  service:
    name: mysql
    state: restarted
