/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILecturerRoom extends Serializable {

    /**
     * Setter for <code>carbondb.lecturer_room.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>carbondb.lecturer_room.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>carbondb.lecturer_room.lecturer_id</code>.
     */
    public void setLecturerId(Long value);

    /**
     * Getter for <code>carbondb.lecturer_room.lecturer_id</code>.
     */
    public Long getLecturerId();

    /**
     * Setter for <code>carbondb.lecturer_room.room_name</code>.
     */
    public void setRoomName(String value);

    /**
     * Getter for <code>carbondb.lecturer_room.room_name</code>.
     */
    public String getRoomName();

    /**
     * Setter for <code>carbondb.lecturer_room.room_detail</code>.
     */
    public void setRoomDetail(String value);

    /**
     * Getter for <code>carbondb.lecturer_room.room_detail</code>.
     */
    public String getRoomDetail();

    /**
     * Setter for <code>carbondb.lecturer_room.begin_datetime</code>.
     */
    public void setBeginDatetime(LocalDateTime value);

    /**
     * Getter for <code>carbondb.lecturer_room.begin_datetime</code>.
     */
    public LocalDateTime getBeginDatetime();

    /**
     * Setter for <code>carbondb.lecturer_room.end_datetime</code>.
     */
    public void setEndDatetime(LocalDateTime value);

    /**
     * Getter for <code>carbondb.lecturer_room.end_datetime</code>.
     */
    public LocalDateTime getEndDatetime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ILecturerRoom
     */
    public void from(org.carbon.sample.ext.jooq.tables.interfaces.ILecturerRoom from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ILecturerRoom
     */
    public <E extends org.carbon.sample.ext.jooq.tables.interfaces.ILecturerRoom> E into(E into);
}
