/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILecturerApplyHistory extends Serializable {

    /**
     * Setter for <code>carbondb.lecturer_apply_history.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>carbondb.lecturer_apply_history.id</code>.
     */
    public Long getId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ILecturerApplyHistory
     */
    public void from(org.carbon.sample.ext.jooq.tables.interfaces.ILecturerApplyHistory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ILecturerApplyHistory
     */
    public <E extends org.carbon.sample.ext.jooq.tables.interfaces.ILecturerApplyHistory> E into(E into);
}
