/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.interfaces;


import java.io.Serializable;
import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public interface IRole extends Serializable {

    /**
     * Setter for <code>carbondb.role.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>carbondb.role.id</code>.
     */
    public Long getId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IRole
     */
    public void from(org.carbon.sample.ext.jooq.tables.interfaces.IRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IRole
     */
    public <E extends org.carbon.sample.ext.jooq.tables.interfaces.IRole> E into(E into);
}
