/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.interfaces.IAsset;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asset implements IAsset {

    private static final long serialVersionUID = -1703058746;

    private Long   id;
    private String assetPath;
    private String assetType;

    public Asset() {}

    public Asset(Asset value) {
        this.id = value.id;
        this.assetPath = value.assetPath;
        this.assetType = value.assetType;
    }

    public Asset(
        Long   id,
        String assetPath,
        String assetType
    ) {
        this.id = id;
        this.assetPath = assetPath;
        this.assetType = assetType;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getAssetPath() {
        return this.assetPath;
    }

    @Override
    public void setAssetPath(String assetPath) {
        this.assetPath = assetPath;
    }

    @Override
    public String getAssetType() {
        return this.assetType;
    }

    @Override
    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Asset (");

        sb.append(id);
        sb.append(", ").append(assetPath);
        sb.append(", ").append(assetType);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAsset from) {
        setId(from.getId());
        setAssetPath(from.getAssetPath());
        setAssetType(from.getAssetType());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAsset> E into(E into) {
        into.from(this);
        return into;
    }
}
