/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.pojos;


import java.time.LocalDateTime;
import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.interfaces.ILecturerRoom;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LecturerRoom implements ILecturerRoom {

    private static final long serialVersionUID = 1184088072;

    private Long id;
    private Long lecturerId;
    private String roomName;
    private String roomDetail;
    private LocalDateTime beginDatetime;
    private LocalDateTime endDatetime;

    public LecturerRoom() {
    }

    public LecturerRoom(LecturerRoom value) {
        this.id = value.id;
        this.lecturerId = value.lecturerId;
        this.roomName = value.roomName;
        this.roomDetail = value.roomDetail;
        this.beginDatetime = value.beginDatetime;
        this.endDatetime = value.endDatetime;
    }

    public LecturerRoom(
            Long id,
            Long lecturerId,
            String roomName,
            String roomDetail,
            LocalDateTime beginDatetime,
            LocalDateTime endDatetime
    ) {
        this.id = id;
        this.lecturerId = lecturerId;
        this.roomName = roomName;
        this.roomDetail = roomDetail;
        this.beginDatetime = beginDatetime;
        this.endDatetime = endDatetime;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public Long getLecturerId() {
        return this.lecturerId;
    }

    @Override
    public void setLecturerId(Long lecturerId) {
        this.lecturerId = lecturerId;
    }

    @Override
    public String getRoomName() {
        return this.roomName;
    }

    @Override
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    @Override
    public String getRoomDetail() {
        return this.roomDetail;
    }

    @Override
    public void setRoomDetail(String roomDetail) {
        this.roomDetail = roomDetail;
    }

    @Override
    public LocalDateTime getBeginDatetime() {
        return this.beginDatetime;
    }

    @Override
    public void setBeginDatetime(LocalDateTime beginDatetime) {
        this.beginDatetime = beginDatetime;
    }

    @Override
    public LocalDateTime getEndDatetime() {
        return this.endDatetime;
    }

    @Override
    public void setEndDatetime(LocalDateTime endDatetime) {
        this.endDatetime = endDatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LecturerRoom (");

        sb.append(id);
        sb.append(", ").append(lecturerId);
        sb.append(", ").append(roomName);
        sb.append(", ").append(roomDetail);
        sb.append(", ").append(beginDatetime);
        sb.append(", ").append(endDatetime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ILecturerRoom from) {
        setId(from.getId());
        setLecturerId(from.getLecturerId());
        setRoomName(from.getRoomName());
        setRoomDetail(from.getRoomDetail());
        setBeginDatetime(from.getBeginDatetime());
        setEndDatetime(from.getEndDatetime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ILecturerRoom> E into(E into) {
        into.from(this);
        return into;
    }
}
