/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.daos;


import java.util.List;
import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.Lecturer;
import org.carbon.sample.ext.jooq.tables.records.LecturerRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LecturerDao extends DAOImpl<LecturerRecord, org.carbon.sample.ext.jooq.tables.pojos.Lecturer, Long> {

    /**
     * Create a new LecturerDao without any configuration
     */
    public LecturerDao() {
        super(Lecturer.LECTURER, org.carbon.sample.ext.jooq.tables.pojos.Lecturer.class);
    }

    /**
     * Create a new LecturerDao with an attached configuration
     */
    public LecturerDao(Configuration configuration) {
        super(Lecturer.LECTURER, org.carbon.sample.ext.jooq.tables.pojos.Lecturer.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.ext.jooq.tables.pojos.Lecturer object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.Lecturer> fetchById(Long... values) {
        return fetch(Lecturer.LECTURER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.ext.jooq.tables.pojos.Lecturer fetchOneById(Long value) {
        return fetchOne(Lecturer.LECTURER.ID, value);
    }

    /**
     * Fetch records that have <code>identityClass IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.Lecturer> fetchByUsername(String... values) {
        return fetch(Lecturer.LECTURER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.Lecturer> fetchByEmail(String... values) {
        return fetch(Lecturer.LECTURER.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public org.carbon.sample.ext.jooq.tables.pojos.Lecturer fetchOneByEmail(String value) {
        return fetchOne(Lecturer.LECTURER.EMAIL, value);
    }

    /**
     * Fetch records that have <code>thumbnail_id IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.Lecturer> fetchByThumbnailId(Long... values) {
        return fetch(Lecturer.LECTURER.THUMBNAIL_ID, values);
    }

    /**
     * Fetch records that have <code>pr_text IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.Lecturer> fetchByPrText(String... values) {
        return fetch(Lecturer.LECTURER.PR_TEXT, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.Lecturer> fetchByPassword(String... values) {
        return fetch(Lecturer.LECTURER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>pr_text_short IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.Lecturer> fetchByPrTextShort(String... values) {
        return fetch(Lecturer.LECTURER.PR_TEXT_SHORT, values);
    }
}
