/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.LecturerApplyHistory;
import org.carbon.sample.ext.jooq.tables.records.LecturerApplyHistoryRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LecturerApplyHistoryDao extends DAOImpl<LecturerApplyHistoryRecord, org.carbon.sample.ext.jooq.tables.pojos.LecturerApplyHistory, Long> {

    /**
     * Create a new LecturerApplyHistoryDao without any configuration
     */
    public LecturerApplyHistoryDao() {
        super(LecturerApplyHistory.LECTURER_APPLY_HISTORY, org.carbon.sample.ext.jooq.tables.pojos.LecturerApplyHistory.class);
    }

    /**
     * Create a new LecturerApplyHistoryDao with an attached configuration
     */
    public LecturerApplyHistoryDao(Configuration configuration) {
        super(LecturerApplyHistory.LECTURER_APPLY_HISTORY, org.carbon.sample.ext.jooq.tables.pojos.LecturerApplyHistory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.ext.jooq.tables.pojos.LecturerApplyHistory object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerApplyHistory> fetchById(Long... values) {
        return fetch(LecturerApplyHistory.LECTURER_APPLY_HISTORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.ext.jooq.tables.pojos.LecturerApplyHistory fetchOneById(Long value) {
        return fetchOne(LecturerApplyHistory.LECTURER_APPLY_HISTORY.ID, value);
    }
}
