/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.LecturerRoom;
import org.carbon.sample.ext.jooq.tables.records.LecturerRoomRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LecturerRoomDao extends DAOImpl<LecturerRoomRecord, org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom, Long> {

    /**
     * Create a new LecturerRoomDao without any configuration
     */
    public LecturerRoomDao() {
        super(LecturerRoom.LECTURER_ROOM, org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom.class);
    }

    /**
     * Create a new LecturerRoomDao with an attached configuration
     */
    public LecturerRoomDao(Configuration configuration) {
        super(LecturerRoom.LECTURER_ROOM, org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom> fetchById(Long... values) {
        return fetch(LecturerRoom.LECTURER_ROOM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom fetchOneById(Long value) {
        return fetchOne(LecturerRoom.LECTURER_ROOM.ID, value);
    }

    /**
     * Fetch records that have <code>lecturer_id IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom> fetchByLecturerId(Long... values) {
        return fetch(LecturerRoom.LECTURER_ROOM.LECTURER_ID, values);
    }

    /**
     * Fetch records that have <code>room_name IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom> fetchByRoomName(String... values) {
        return fetch(LecturerRoom.LECTURER_ROOM.ROOM_NAME, values);
    }

    /**
     * Fetch records that have <code>room_detail IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom> fetchByRoomDetail(String... values) {
        return fetch(LecturerRoom.LECTURER_ROOM.ROOM_DETAIL, values);
    }

    /**
     * Fetch records that have <code>begin_datetime IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom> fetchByBeginDatetime(LocalDateTime... values) {
        return fetch(LecturerRoom.LECTURER_ROOM.BEGIN_DATETIME, values);
    }

    /**
     * Fetch records that have <code>end_datetime IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerRoom> fetchByEndDatetime(LocalDateTime... values) {
        return fetch(LecturerRoom.LECTURER_ROOM.END_DATETIME, values);
    }
}
