/**
 * This class is generated by jOOQ
 */
package org.carbon.sample.ext.jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.carbon.sample.ext.jooq.tables.LecturerSchedule;
import org.carbon.sample.ext.jooq.tables.records.LecturerScheduleRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LecturerScheduleDao extends DAOImpl<LecturerScheduleRecord, org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule, Long> {

    /**
     * Create a new LecturerScheduleDao without any configuration
     */
    public LecturerScheduleDao() {
        super(LecturerSchedule.LECTURER_SCHEDULE, org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule.class);
    }

    /**
     * Create a new LecturerScheduleDao with an attached configuration
     */
    public LecturerScheduleDao(Configuration configuration) {
        super(LecturerSchedule.LECTURER_SCHEDULE, org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule> fetchById(Long... values) {
        return fetch(LecturerSchedule.LECTURER_SCHEDULE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule fetchOneById(Long value) {
        return fetchOne(LecturerSchedule.LECTURER_SCHEDULE.ID, value);
    }

    /**
     * Fetch records that have <code>begin_datetime IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule> fetchByBeginDatetime(LocalDateTime... values) {
        return fetch(LecturerSchedule.LECTURER_SCHEDULE.BEGIN_DATETIME, values);
    }

    /**
     * Fetch records that have <code>end_datetime IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule> fetchByEndDatetime(LocalDateTime... values) {
        return fetch(LecturerSchedule.LECTURER_SCHEDULE.END_DATETIME, values);
    }

    /**
     * Fetch records that have <code>lecturer_id IN (values)</code>
     */
    public List<org.carbon.sample.ext.jooq.tables.pojos.LecturerSchedule> fetchByLecturerId(Long... values) {
        return fetch(LecturerSchedule.LECTURER_SCHEDULE.LECTURER_ID, values);
    }
}
