/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.carbon.sample.heroku.ext.jooq.tables.Todo;
import org.carbon.sample.heroku.ext.jooq.tables.records.TodoRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoDao extends DAOImpl<TodoRecord, org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo, Long> {

    /**
     * Create a new TodoDao without any configuration
     */
    public TodoDao() {
        super(Todo.TODO, org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo.class);
    }

    /**
     * Create a new TodoDao with an attached configuration
     */
    public TodoDao(Configuration configuration) {
        super(Todo.TODO, org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo> fetchById(Long... values) {
        return fetch(Todo.TODO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo fetchOneById(Long value) {
        return fetchOne(Todo.TODO.ID, value);
    }

    /**
     * Fetch records that have <code>text IN (values)</code>
     */
    public List<org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo> fetchByText(String... values) {
        return fetch(Todo.TODO.TEXT, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo> fetchByUserId(Long... values) {
        return fetch(Todo.TODO.USER_ID, values);
    }

    /**
     * Fetch records that have <code>available IN (values)</code>
     */
    public List<org.carbon.sample.heroku.ext.jooq.tables.pojos.Todo> fetchByAvailable(Boolean... values) {
        return fetch(Todo.TODO.AVAILABLE, values);
    }
}
