#
# app.yml
#

- hosts: app
  remote_user: ansible
  gather_facts: false
  become: true
  vars_files:
    - env_vars/{{ stage }}.yml
    - env_vars/secrets/{{ stage }}.yml
  roles:
    - db
    - web
