/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBlog extends Serializable {

    /**
     * Setter for <code>carbon.blog.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>carbon.blog.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>carbon.blog.title</code>.
     */
    public void setTitle(String value);

    /**
     * Getter for <code>carbon.blog.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>carbon.blog.summary</code>.
     */
    public void setSummary(String value);

    /**
     * Getter for <code>carbon.blog.summary</code>.
     */
    public String getSummary();

    /**
     * Setter for <code>carbon.blog.content</code>.
     */
    public void setContent(String value);

    /**
     * Getter for <code>carbon.blog.content</code>.
     */
    public String getContent();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IBlog
     */
    public void from(org.carbon.sample.heroku.ext.jooq.tables.interfaces.IBlog from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IBlog
     */
    public <E extends org.carbon.sample.heroku.ext.jooq.tables.interfaces.IBlog> E into(E into);
}
