/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.heroku.ext.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITodo extends Serializable {

    /**
     * Setter for <code>carbon.todo.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>carbon.todo.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>carbon.todo.text</code>.
     */
    public void setText(String value);

    /**
     * Getter for <code>carbon.todo.text</code>.
     */
    public String getText();

    /**
     * Setter for <code>carbon.todo.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>carbon.todo.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>carbon.todo.available</code>.
     */
    public void setAvailable(Boolean value);

    /**
     * Getter for <code>carbon.todo.available</code>.
     */
    public Boolean getAvailable();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITodo
     */
    public void from(org.carbon.sample.heroku.ext.jooq.tables.interfaces.ITodo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITodo
     */
    public <E extends org.carbon.sample.heroku.ext.jooq.tables.interfaces.ITodo> E into(E into);
}
