/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.interfaces.IAuthClient;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthClient implements IAuthClient {

    private static final long serialVersionUID = 208259880;

    private Long   id;
    private String clientHost;
    private String clientId;

    public AuthClient() {}

    public AuthClient(AuthClient value) {
        this.id = value.id;
        this.clientHost = value.clientHost;
        this.clientId = value.clientId;
    }

    public AuthClient(
        Long   id,
        String clientHost,
        String clientId
    ) {
        this.id = id;
        this.clientHost = clientHost;
        this.clientId = clientId;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getClientHost() {
        return this.clientHost;
    }

    @Override
    public void setClientHost(String clientHost) {
        this.clientHost = clientHost;
    }

    @Override
    public String getClientId() {
        return this.clientId;
    }

    @Override
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthClient (");

        sb.append(id);
        sb.append(", ").append(clientHost);
        sb.append(", ").append(clientId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAuthClient from) {
        setId(from.getId());
        setClientHost(from.getClientHost());
        setClientId(from.getClientId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAuthClient> E into(E into) {
        into.from(this);
        return into;
    }
}
