/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.interfaces.IRockettyRanking;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyRanking implements IRockettyRanking {

    private static final long serialVersionUID = 1989700696;

    private Long    id;
    private String  internalUserId;
    private Integer score;
    private String  displayName;

    public RockettyRanking() {}

    public RockettyRanking(RockettyRanking value) {
        this.id = value.id;
        this.internalUserId = value.internalUserId;
        this.score = value.score;
        this.displayName = value.displayName;
    }

    public RockettyRanking(
        Long    id,
        String  internalUserId,
        Integer score,
        String  displayName
    ) {
        this.id = id;
        this.internalUserId = internalUserId;
        this.score = score;
        this.displayName = displayName;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getInternalUserId() {
        return this.internalUserId;
    }

    @Override
    public void setInternalUserId(String internalUserId) {
        this.internalUserId = internalUserId;
    }

    @Override
    public Integer getScore() {
        return this.score;
    }

    @Override
    public void setScore(Integer score) {
        this.score = score;
    }

    @Override
    public String getDisplayName() {
        return this.displayName;
    }

    @Override
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RockettyRanking (");

        sb.append(id);
        sb.append(", ").append(internalUserId);
        sb.append(", ").append(score);
        sb.append(", ").append(displayName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IRockettyRanking from) {
        setId(from.getId());
        setInternalUserId(from.getInternalUserId());
        setScore(from.getScore());
        setDisplayName(from.getDisplayName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IRockettyRanking> E into(E into) {
        into.from(this);
        return into;
    }
}
