/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.interfaces.IRockettyRanking;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyRanking implements IRockettyRanking {

    private static final long serialVersionUID = 312078102;

    private final Long    id;
    private final Long    rockettyUserId;
    private final Integer score;

    public RockettyRanking(RockettyRanking value) {
        this.id = value.id;
        this.rockettyUserId = value.rockettyUserId;
        this.score = value.score;
    }

    public RockettyRanking(
        Long    id,
        Long    rockettyUserId,
        Integer score
    ) {
        this.id = id;
        this.rockettyUserId = rockettyUserId;
        this.score = score;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Long getRockettyUserId() {
        return this.rockettyUserId;
    }

    @Override
    public Integer getScore() {
        return this.score;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RockettyRanking (");

        sb.append(id);
        sb.append(", ").append(rockettyUserId);
        sb.append(", ").append(score);

        sb.append(")");
        return sb.toString();
    }
}
