/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.interfaces.IRockettyUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RockettyUser implements IRockettyUser {

    private static final long serialVersionUID = 661714821;

    private final Long   id;
    private final Long   rockettyAuthClientId;
    private final String displayName;

    public RockettyUser(RockettyUser value) {
        this.id = value.id;
        this.rockettyAuthClientId = value.rockettyAuthClientId;
        this.displayName = value.displayName;
    }

    public RockettyUser(
        Long   id,
        Long   rockettyAuthClientId,
        String displayName
    ) {
        this.id = id;
        this.rockettyAuthClientId = rockettyAuthClientId;
        this.displayName = displayName;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Long getRockettyAuthClientId() {
        return this.rockettyAuthClientId;
    }

    @Override
    public String getDisplayName() {
        return this.displayName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RockettyUser (");

        sb.append(id);
        sb.append(", ").append(rockettyAuthClientId);
        sb.append(", ").append(displayName);

        sb.append(")");
        return sb.toString();
    }
}
