/*
 * This file is generated by jOOQ.
*/
package org.carbon.sample.v2.ext.jooq.tables.pojos;


import javax.annotation.Generated;

import org.carbon.sample.v2.ext.jooq.tables.interfaces.IUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements IUser {

    private static final long serialVersionUID = -1729763149;

    private final Long   id;
    private final String email;
    private final String userName;
    private final String password;

    public User(User value) {
        this.id = value.id;
        this.email = value.email;
        this.userName = value.userName;
        this.password = value.password;
    }

    public User(
        Long   id,
        String email,
        String userName,
        String password
    ) {
        this.id = id;
        this.email = email;
        this.userName = userName;
        this.password = password;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public String getUserName() {
        return this.userName;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
